name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: thepwagner-org/.github/.github/workflows/my-action.yml@main
        with:
          image: meow
