name: Build
on:
  push:
    ignore-branches:
      - main

env:
  IMAGE_REPO: ghcr.io/thepwagner-org/debian-bullseye

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${{env.IMAGE_REPO}}:${{github.sha}} .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          docker push ${{env.IMAGE_REPO}}:${{github.sha}}
