name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@37f0bb56562d3cb69b27ad0d72b04fc9eba647dd # tag=v1.0.0
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}

