name: Build
on:
  push:

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: thepwagner-org/.github/.github/workflows/build.yaml@main
        with:
          image: meow
