name: Build
on:
  push:
jobs:
  test:
    runs-on: self-hosted
    env:
      IMAGE: debian-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t $IMAGE .
      - name: scan
        uses: aquasecurity/trivy-action@8eccb5539730451af599c84f444c6d6cf0fc2bb0
        with:
          image-ref: ${{env.IMAGE}}'
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
