name: Build
on:
  push:

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@main
    with:
      image: meow
