name: Build
on:
  push:

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: thepwagner-org/.github/.github/workflows/build.yaml@main
        with:
          image: meow
  wtf:
    runs-on: ubuntu-latest
    steps:
      - name: "🌎 Fetching code"
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          fetch-depth: 0
          persist-credentials: false
