name: Build
on:
  push:
jobs:
  test:
    runs-on: self-hosted
    env:
      IMAGE: debian-bullseye
      REGISTRY: registry.k8s.pwagner.net
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t "$REGISTRY/library/$IMAGE" .
      - name: Scan
        uses: docker://registry.k8s.pwagner.net/library/trivy:latest
        with:
          args: "$${{env.REGISTRY}}/library/$${{env.IMAGE}}"
      - name: Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: robot$github-actions
          password: ${{secrets.REGISTRY_K8S_PASSWORD}}
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: docker push "$REGISTRY/library/$IMAGE"
