name: Build
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    env:
      IMAGE: debian-bullseye
      REGISTRY: registry.k8s.pwagner.net
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker pull "$REGISTRY/library/$IMAGE:latest"
          docker build --cache-from "$REGISTRY/library/$IMAGE:latest" -t "$REGISTRY/library/$IMAGE" .
      - name: Scan
        uses: docker://registry.k8s.pwagner.net/library/trivy:latest@sha256:612efcc0468d64af645f47280565ed6e85113d112c47e14e4f6f396e23f67662
        with:
          args: "${{env.REGISTRY}}/library/${{env.IMAGE}}"
      - name: Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: robot$github-actions
          password: ${{secrets.REGISTRY_K8S_PASSWORD}}
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: docker push "$REGISTRY/library/$IMAGE"
