name: Build
on:
  push:
jobs:
  test:
    runs-on: self-hosted
    env:
      IMAGE: debian-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t $IMAGE .
