name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${{github.repository}}:${{github.sha}} .

      # Always run Syft
      - uses: anchore/sbom-action/download-syft@ce4a7cf05d7b684693d7b6bba97bfbee56806edb # v0.7.0
      - run: syft packages -o spdx-json=sbom.spdx.json ${{github.repository}}:${{github.sha}}
      
      # TODO: On PRs, run Grype and report the result
      
      # TODO: On master, push the image and SBOM
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          # Upload SBOM
          DIGEST=$(docker inspect --format='{{.Id}}' ${{github.repository}}:${{github.sha}})
          SBOM_TAG=$(echo $DIGEST | sed -e 's/:/_/g').spdx.json
          oras push ghcr.io/thepwagner-org/debian-bullseye:${SBOM_TAG} \
              ./sbom.spdx.json:application/spdx+json

          # Push the image and update tag
          docker tag ${DIGEST} ghcr.io/thepwagner-org/debian-bullseye:latest
          docker push ghcr.io/thepwagner-org/debian-bullseye:latest
