name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@aa7a4cf9d36faf33af77b64921afe7a77b2427fe # v2.3.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
