name: Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 4 * * *'

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  check:
    uses: thepwagner-org/actions/.github/workflows/check.yaml@7a8c48d526143c8b058cd97476f7fcea16deb674 # v2.9.0
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}
