name: Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 4 * * *'

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  check:
    uses: thepwagner-org/actions/.github/workflows/check.yaml@21218e61b841c17ddd74dace7413b3c73a854592 # v2.8.0
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}
