name: Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 4 * * *'

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  check:
    uses: thepwagner-org/actions/.github/workflows/check.yaml@29fc277227ae3fc735e9ac7790d307f0516a70c3 # v3.0.0
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}
