name: Publish
on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: ghcr.io/thepwagner-org/debian-bullseye

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - run: docker build -t ${{env.IMAGE_REPO}}:latest .
      - uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          docker push ${{env.IMAGE_REPO}}:latest
