name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  publish:
    uses: thepwagner-org/actions/.github/workflows/publish.yaml@v1.0.2
    secrets:
      token: ${{secrets.WAPWAGNER_TOKEN}}
