name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: thepwagner-org/actions/.github/workflows/publish.yaml@external-sboms
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
