name: Rebuild
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    env:
      IMAGE: debian-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build --no-cache -t $IMAGE .
