name: Scorecard analysis workflow
on:
  branch_protection_rule:
  schedule:
    # TODO: probably distribute this
    - cron: '30 1 * * 6'
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - uses: thepwagner/token-action@7064f486c7bd204fc7ab56da53d202d2352a1dba # tag=v0.1.0
        id: token
        with:
          server: 'https://gtfo-yuiafdvuwa-uc.a.run.app'
          repositories: |
            - thepwagner-org/debian
          permissions: |
            administration: read
            metadata: read
            repository_hooks: read

      - name: "Run analysis"
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{steps.token.outputs.token}}
          publish_results: true
