name: Scorecard analysis workflow
on:
  branch_protection_rule:
  schedule:
    # TODO: probably distribute this
    - cron: '30 1 * * 6'
  push:
    branches: main
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
        with:
          # TODO: gtfo?
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
